# General SEO settings.
title: Davor Bonaci
description: "Davor Bonaci's personal website"
url: https://davorbonaci.com
baseurl: ""
favicon: /images/favicon.ico

# Author settings.
author:
  name      : Davor Bonaci
  job       : CEO at <a href="https://kaskada.com">Kaskada</a>
  bio       : I'm a co-founder and CEO of a Seattle-based startup, previously chair of the <a href="https://beam.apache.org">Apache Beam</a> PMC and software engineer in Google Cloud.
  thumb     : /images/davor.jpg
  github    : https://github.com/davorbonaci
  twitter   : https://twitter.com/BonaciDavor
  linkedin  : https://www.linkedin.com/in/davorbonaci

# Specify source location.
sass:
  sass_dir: _scss
  style: compressed # expanded
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Build settings.
permalink: /blog/:year/:title/
paginate: 3
paginate_path: "/blog/page/:num/"
gems:
  - jekyll-paginate
comments: true

markdown: kramdown
highlighter: rouge

# GitHub pages.
repository: davorbonaci/davorbonaci.github.io

# External services.
google_analytics: UA-82528307-1
disqus_shortname: "davorbonaci"
disqus_site_shortname: "davorbonaci"

# Menu.
navbar:
  - slug: about
    title: About
  # - slug: beam-dataflow
  #  title: Beam & Dataflow
  # - slug: blog
  #  title: Blog
